[[spheroidal_backend_double]]
arch = "aarch64"
git-tree-sha1 = "62bc9c03c3ed629de8d3ce9b5616ab1af26cf384"
os = "macos"

    [[spheroidal_backend_double.download]]
    sha256 = "510a4e63ceefc71015e432ad9dc76dd59b5c2a5c1ffae07877777f920a5dbb42"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_double-aarch64-apple-darwin.tar.gz"
[[spheroidal_backend_double]]
arch = "x86_64"
git-tree-sha1 = "12a4910866644e53cb6c116e04275e293c1a854a"
os = "macos"

    [[spheroidal_backend_double.download]]
    sha256 = "3250a360425a584aaa2ddc2fadf713087a7d0bc655cd6d3a58451f99b0d1d043"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_double-x86_64-apple-darwin.tar.gz"
[[spheroidal_backend_double]]
arch = "x86_64"
git-tree-sha1 = "35404d3676a0b36c6306bb6e0c58de50be73133c"
libc = "glibc"
os = "linux"

    [[spheroidal_backend_double.download]]
    sha256 = "5085bb309618f792024c7f74830ced9b8a7bdfcf7121b568d07fe40ea59addb0"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_double-x86_64-linux-gnu.tar.gz"
[[spheroidal_backend_double]]
arch = "x86_64"
git-tree-sha1 = "ccb246bddf89c32166f90d6a0615cdcad56208a0"
os = "windows"

    [[spheroidal_backend_double.download]]
    sha256 = "89de5b18d495428af465a501adeef386cb41dc10f7c03089e2b646878d629dd5"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_double-x86_64-w64-mingw32.tar.gz"

[[spheroidal_backend_quad]]
arch = "aarch64"
git-tree-sha1 = "1e8c46e0d25df46bdd9bddcb8e12eaf6b70d403a"
os = "macos"

    [[spheroidal_backend_quad.download]]
    sha256 = "a0914246bd77a417ad287557d37ae8a7c8238afacecc4186c4185a5759089383"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_quad-aarch64-apple-darwin.tar.gz"
[[spheroidal_backend_quad]]
arch = "x86_64"
git-tree-sha1 = "3dd66f000671482857dc8fc2e2f104818d10e490"
os = "macos"

    [[spheroidal_backend_quad.download]]
    sha256 = "eba4c372572950c6ddaa975eff1468c0a32a52cbf2f615e23835ec2dfc4e8311"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_quad-x86_64-apple-darwin.tar.gz"
[[spheroidal_backend_quad]]
arch = "x86_64"
git-tree-sha1 = "cb529aa4ffba427abf7068af9c1d6c86baf9e40a"
libc = "glibc"
os = "linux"

    [[spheroidal_backend_quad.download]]
    sha256 = "121f6ca63459dc48174f65b9d0927d15863b89457756b40708c9aeddedb38412"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_quad-x86_64-linux-gnu.tar.gz"
[[spheroidal_backend_quad]]
arch = "x86_64"
git-tree-sha1 = "836488264b5061e1a689b482c78d0081b574e317"
os = "windows"

    [[spheroidal_backend_quad.download]]
    sha256 = "4b012a466a70d548f23f875f59330e480cfe04ffae819589e6f6dbc9231c27eb"
    url = "https://github.com/brandynlucca/SpheroidalWaves.jl/releases/download/backends-v0.4.1-1/spheroidal_backend_quad-x86_64-w64-mingw32.tar.gz"
