# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "4d78d53520a132dd4bb07929e0e9e7b059db0e49"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.SpheroidalWaves]]
deps = ["Artifacts", "Libdl"]
path = "."
uuid = "5995e872-983e-498e-9750-1cefbd4fb98d"
version = "0.2.3"
