name = "SpheroidalWaveFunctions"
uuid = "5995e872-983e-498e-9750-1cefbd4fb98d"
authors = ["brandynlucca <brandyn.lucca@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
