name = "SpheroidalWaves"
uuid = "5995e872-983e-498e-9750-1cefbd4fb98d"
authors = ["brandynlucca <brandyn.lucca@gmail.com> and contributors"]
version = "0.5.1"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpheroidalWaves_jll = "a34cad3f-f691-5efd-970c-48ef20c3665d"

[compat]
julia = "1.10"
SpheroidalWaves_jll = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
